add instruction for self-hosted SAML Authentication Options
getredash/website pull request #567
Opened 2021-04-30 14:19 UTC by iamtodor

Hello,
This PR brings huge documentation improvement and clarification for SSO SAML Authentication.
PR has been established based on the opened issue https://github.com/getredash/redash/issues/2977
Kudos to @rockxsj

2021-05-03 18:36 UTC, susodapop requested changes
A couple small changes and we can merge this.

Thanks!

2021-05-03 18:36 UTC, susodapop commented on src/pages/kb/user-guide/users/authentication-options.md
> +   `http://your-site.com/auth/realms/somerelm/protocol/saml/descriptor`
This isn't strictly true. The metadata URL should point at an XML file. Perhaps update to the following?

```suggestion
1. SAML Metadata URL should point to an XML file on your server, such as:
   `http://your-site.com/auth/realms/somerelm/protocol/saml/descriptor`
```

2021-05-03 18:36 UTC, susodapop commented on src/pages/kb/user-guide/users/authentication-options.md
> +2. SAML Entity ID has to be: `redash`
```suggestion
2. SAML Entity ID should be: `redash`
```

2021-05-03 18:36 UTC, susodapop commented on src/pages/kb/user-guide/users/authentication-options.md
> +3. SAML NameID Format has to be:
```suggestion
3. SAML NameID Format should be:
```

2021-05-03 20:38 UTC, iamtodor commented
@susodapop Thank you for the changes! I committed them

2021-05-03 21:10 UTC, susodapop approved these changes
LGTM

2021-05-03 21:10 UTC, merged

2021-05-04 07:37 UTC, iamtodor commented
@susodapop awesome, thank you! :)