Add a health checkpoint API for redash
getredash/website pull request #622
Opened 2021-12-01 14:42 UTC by kurianbenoy-aot

2021-12-01 14:44 UTC, susodapop requested changes
Looks good. Just style nits.

2021-12-01 14:44 UTC, susodapop commented on src/pages/kb/open-source/dev-guide/docker.md
> +After your installation is complete, you can do the healthcheck by calling **/ping** API endpoint.
```suggestion
After your installation is complete, you can do the healthcheck by calling `/ping` API endpoint.
```

2021-12-01 14:44 UTC, susodapop commented on src/pages/kb/open-source/dev-guide/setup.md
> +After your installation is complete, you can do the healthcheck by calling **/ping** API endpoint.
```suggestion
After your installation is complete, you can do the healthcheck by calling `/ping` API endpoint.
```

2021-12-01 14:44 UTC, susodapop commented on src/pages/kb/open-source/setup.md
> +After your installation is complete, you can do the healthcheck by calling **/ping** API endpoint.
```suggestion
After your installation is complete, you can do the healthcheck by calling `/ping` API endpoint.
```

2021-12-01 14:55 UTC, kurianbenoy-aot commented
Oh that was quick @susodapop. Have addressed your style comments.

2021-12-01 19:13 UTC, susodapop approved these changes

2021-12-13 18:20 UTC, merged

2021-12-14 04:45 UTC, kurianbenoy-aot commented
First PR merged to Redash. Super happy about it :)