Update env-vars-settings.md
getredash/website pull request #676
Opened 2023-07-18 10:16 UTC by gaecoli

https://github.com/getredash/redash/commit/bbd0a21831d04562c769e4b6b3693c062b146654

2023-07-18 10:32 UTC, justinclift requested changes

2023-07-18 10:32 UTC, justinclift commented on src/pages/kb/open-source/admin-guide/env-vars-settings.md
> +| `REDASH_QUERY_RESULTS_EXPIRED_TTL_ENABLED`      | Enable the query result set default qupired ttl.
Typo in `qupired`. :wink:

2023-07-25 07:25 UTC, gaecoli commented on src/pages/kb/open-source/admin-guide/env-vars-settings.md
> +| `REDASH_QUERY_RESULTS_EXPIRED_TTL_ENABLED`      | Enable the query result set default qupired ttl.
fixed!

2023-07-25 07:58 UTC, justinclift commented on src/pages/kb/open-source/admin-guide/env-vars-settings.md
> +| `REDASH_QUERY_RESULTS_EXPIRED_TTL_ENABLED`      | Enable the query result set default qupired ttl.
Cool, looks good to me. :smile:

2023-07-25 07:58 UTC, justinclift approved these changes

2023-07-25 07:58 UTC, merged